double Cpi_cal(int sp, double T);
double Hgi_cal(int sp, double T);
double viscogical(int sp, double T);
double phical(int sp1, int sp2, double *mui);
double viscogcal(double T, double *X);
double lamdagcal(double T, double *X);
double Dij_cal(int i, int j, double T, double P);
void Diffusion_cal(double *Dsp, double T, double P, double *X);
double dHv_cal(double T);
double lamdalcal(double T);
double Cplcal(double T);
